window.MARKET_BRIEFING_DATA = {
  date: "2026-06-06",
  time: "08:30 北京时间",
  lastUpdated: null,
  apiBase: "https://daily-briefing-blue.vercel.app",
  refreshInterval: 10000,
  oneLine: "没有真实行情接口时，不按页面价格交易；今天先降贵金属集中度，再考虑军工小仓切换。",
  tradeDecision: [
    {
      type: "先卖",
      title: "黄金LOF 164701",
      conclusion: "只在真实行情触发价到达后卖2-3手。",
      action: "真实成交价到1.765卖2手，1.774上方可卖3手。",
      trigger: "真实行情不到1.765不动。",
      reason: "贵金属仓位偏重，优先降集中度。"
    },
    {
      type: "再卖",
      title: "国投白银LOF 161226",
      conclusion: "不补仓，只等真实反弹价减1手。",
      action: "真实成交价到2.132上方卖1手。",
      trigger: "不到2.132不动。",
      reason: "白银波动更大，补仓会放大回撤。"
    },
    {
      type: "再买",
      title: "军工龙头ETF 512710",
      conclusion: "只允许用卖出资金买1手。",
      action: "尾盘真实价格站稳0.696且强于大盘再买。",
      trigger: "没有卖出资金、没有真实行情或没有站稳0.696，不买。",
      reason: "满仓账户不能凭感觉加仓。"
    },
    {
      type: "禁止",
      title: "恒生科技 / 稀有金属",
      conclusion: "今天不新增。",
      action: "只看关键位，不追。",
      trigger: "恒生科技站上0.628也只是持有信号。",
      reason: "已有底仓，继续加会提高集中度。"
    }
  ],
  executionOrder: [
    "1. 先确认页面是否显示实时、午间休市、已收盘、历史数据或停牌；如果显示接口失败，不按价格执行。",
    "2. 黄金164701真实价格到1.765，才考虑卖2手。",
    "3. 白银161226真实价格到2.132，才考虑卖1手。",
    "4. 已卖出资金后，再看512710是否站稳0.696。"
  ],
  noTradeList: [
    "不在真实行情失败时追买。",
    "不因亏损深补白银。",
    "不在没有现金来源时买新方向。",
    "不把主观评分当成真实行情。"
  ],
  holdings: [
    {
      name: "恒生科技ETF大成",
      code: "159740",
      symbol: "SZ159740",
      market: "SZ",
      type: "exchange_fund",
      sector: "港股科技",
      support: "0.600",
      resistance: "0.628",
      action: "持有，不加仓",
      invalidCondition: "跌破0.600且港股科技权重同步走弱",
      predictionScore: 5,
      predictionLabel: "中性",
      expectedDirection: "震荡",
      reason: "仓位较高，未突破关键压力位。",
      riskLevel: "中"
    },
    {
      name: "黄金LOF",
      code: "164701",
      symbol: "SZ164701",
      market: "SZ",
      type: "exchange_fund",
      sector: "黄金",
      support: "1.720",
      resistance: "1.765 / 1.774",
      action: "反弹到价卖2-3手",
      invalidCondition: "美元、美债同步走弱且黄金强势放量",
      predictionScore: 4,
      predictionLabel: "轻度看跌",
      expectedDirection: "看跌",
      reason: "贵金属集中度偏高，先降风险。",
      riskLevel: "中"
    },
    {
      name: "军工龙头ETF富国",
      code: "512710",
      symbol: "SH512710",
      market: "SH",
      type: "exchange_fund",
      sector: "军工",
      support: "0.686",
      resistance: "0.696",
      action: "有卖出资金才买1手",
      invalidCondition: "冲高回落并弱于大盘",
      predictionScore: 7,
      predictionLabel: "轻度看涨",
      expectedDirection: "看涨",
      reason: "相对强度好，但必须尾盘确认。",
      riskLevel: "中"
    },
    {
      name: "国投白银LOF",
      code: "161226",
      symbol: "SZ161226",
      market: "SZ",
      type: "exchange_fund",
      sector: "白银",
      support: "2.080",
      resistance: "2.132",
      action: "不补仓，反弹卖1手",
      invalidCondition: "白银放量站回2.132并强于黄金",
      predictionScore: 3,
      predictionLabel: "轻度看跌",
      expectedDirection: "看跌",
      reason: "亏损深但波动更大，不适合补仓。",
      riskLevel: "高"
    },
    {
      name: "稀有金属ETF广发",
      code: "159608",
      symbol: "SZ159608",
      market: "SZ",
      type: "exchange_fund",
      sector: "稀有金属",
      support: "1.190",
      resistance: "1.224",
      action: "观察，不加仓",
      invalidCondition: "跌破1.190且锂矿板块走弱",
      predictionScore: 5,
      predictionLabel: "中性",
      expectedDirection: "震荡",
      reason: "已有资源品敞口，等突破再看。",
      riskLevel: "中"
    },
    {
      name: "航空航天ETF天弘",
      code: "159241",
      symbol: "SZ159241",
      market: "SZ",
      type: "exchange_fund",
      sector: "航空航天",
      support: "1.171",
      resistance: "1.200",
      action: "小仓持有",
      invalidCondition: "军工主线转弱",
      predictionScore: 6,
      predictionLabel: "轻度看涨",
      expectedDirection: "看涨",
      reason: "方向跟随军工，但仓位小。",
      riskLevel: "中"
    },
    {
      name: "电力ETF银华",
      code: "562350",
      symbol: "SH562350",
      market: "SH",
      type: "exchange_fund",
      sector: "电力",
      support: "1.240",
      resistance: "1.280",
      action: "小仓观察",
      invalidCondition: "防守板块继续走弱",
      predictionScore: 5,
      predictionLabel: "中性",
      expectedDirection: "震荡",
      reason: "小仓防守，今天不是主线。",
      riskLevel: "低"
    }
  ],
  watchlist: [
    {
      name: "中国联通",
      code: "600050",
      symbol: "SH600050",
      market: "SH",
      type: "stock",
      sector: "通信/6G",
      status: "观察，不买",
      reason: "通信方向有政策催化。",
      buyTrigger: "连续两天强于大盘且放量突破短压。",
      avoidReason: "第一天消息刺激不追。",
      risk: "低价股也会高开低走。",
      support: "4.98",
      resistance: "5.28",
      predictionScore: 5,
      predictionLabel: "中性",
      expectedDirection: "震荡",
      action: "观察，不追",
      invalidCondition: "跌破支撑并缩量走弱",
      riskLevel: "中"
    },
    {
      name: "天齐锂业",
      code: "002466",
      symbol: "SZ002466",
      market: "SZ",
      type: "stock",
      sector: "锂矿",
      status: "观察，不买",
      reason: "资源股有弹性，但账户已有稀有金属ETF。",
      buyTrigger: "锂矿板块放量转强，159608同步站上1.224。",
      avoidReason: "单股波动大，当前账户已满仓。",
      risk: "资源品价格反复。",
      support: "30.80",
      resistance: "33.20",
      predictionScore: 5,
      predictionLabel: "中性",
      expectedDirection: "震荡",
      action: "观察，不追",
      invalidCondition: "锂矿板块继续弱于大盘",
      riskLevel: "高"
    },
    {
      name: "中芯国际",
      code: "688981",
      symbol: "SH688981",
      market: "SH",
      type: "stock",
      sector: "半导体",
      status: "观察，不买",
      reason: "芯片若连续强于大盘可关注。",
      buyTrigger: "板块连续两天强于大盘且成交放大。",
      avoidReason: "单日反弹不买。",
      risk: "高位分化。",
      support: "71.50",
      resistance: "76.80",
      predictionScore: 5,
      predictionLabel: "中性",
      expectedDirection: "震荡",
      action: "观察，不追",
      invalidCondition: "半导体板块冲高回落",
      riskLevel: "高"
    }
  ],
  riskOverview: [
    { title: "最大风险", priority: "高", conclusion: "贵金属集中度偏高。", trigger: "黄金、白银同时弱于预期。", action: "只在真实反弹触发价减，不下跌补。" },
    { title: "行情风险", priority: "高", conclusion: "没有真实行情就不能按价格交易。", trigger: "页面显示接口失败或暂无真实数据。", action: "打开券商App核对，不用页面价格。" },
    { title: "满仓风险", priority: "中", conclusion: "追新方向会让仓位失控。", trigger: "没有卖出资金还想买军工或新热点。", action: "强制先卖后买。" }
  ],
  newsItems: [],
  newsFlow: [],
  reasoning: [
    { title: "行情信号", basis: "真实价格、涨跌幅、成交量和最近交易日K线。", inference: "价格在支撑上方且缩量时，先看持有；放量跌破支撑时先防守。", conclusion: "没有触发价就不交易。", invalidCondition: "接口失败且无缓存，所有价格判断暂停。" },
    { title: "K线信号", basis: "日K、近5日和近20日涨跌幅。", inference: "短线转强但未突破压力位时，容易冲高回落。", conclusion: "突破前不追，突破后也要看成交量。", invalidCondition: "突破当天高开低走或放量下跌。" },
    { title: "新闻信号", basis: "真实新闻来源、发布时间、相关标的和影响方向。", inference: "利好需要盘面确认，利空先降低预期。", conclusion: "新闻改变评分，不直接替代交易触发价。", invalidCondition: "新闻被澄清、证伪或价格反向运行。" },
    { title: "仓位信号", basis: "账户接近满仓，贵金属和资源品敞口偏高。", inference: "新增方向必须先释放资金，否则会放大回撤。", conclusion: "先卖后买，禁止无现金来源追新方向。", invalidCondition: "银证转入或已卖出形成可用现金。" }
  ],
  invalidConditions: [
    "真实行情失败，所有价格触发计划暂停。",
    "黄金未到1.765，减仓计划不执行。",
    "白银未到2.132，不卖也不补。",
    "军工未站稳0.696，买1手计划作废。"
  ],
  learningFramework: [
    { title: "支撑位", basis: "价格多次回踩不破的位置。", inference: "跌破支撑说明承接变弱。", conclusion: "支撑上方观察，跌破先防守。", invalidCondition: "跌破后快速放量收回。" },
    { title: "压力位", basis: "价格多次冲高回落的位置。", inference: "未突破压力前，追高胜率不高。", conclusion: "放量站上压力再考虑加仓。", invalidCondition: "突破后缩量回落到压力位下方。" },
    { title: "放量突破", basis: "价格上破关键位且成交量明显放大。", inference: "资金愿意用更高价格买入。", conclusion: "可从观察升级为条件买入。", invalidCondition: "放量后高开低走或次日跌回关键位。" },
    { title: "消息兑现", basis: "新闻利好出现后股价不涨反跌。", inference: "资金可能提前交易过预期。", conclusion: "利好不追，必须看盘面承接。", invalidCondition: "后续继续放量创新高。" }
  ],
  nextWatch: [
    { title: "164701 黄金LOF", body: "明天继续看1.765/1.774能否触发减仓。" },
    { title: "512710 军工龙头ETF", body: "明天看0.696上方是否能站稳。" },
    { title: "159608 稀有金属ETF", body: "明天看1.224是否放量突破，否则不加。" }
  ],
  searchUniverse: [
    { name: "东材科技", code: "601208", symbol: "SH601208", market: "SH", type: "stock", sector: "新材料", support: "8.20", resistance: "8.80" },
    { name: "天齐锂业", code: "002466", symbol: "SZ002466", market: "SZ", type: "stock", sector: "锂矿", support: "30.80", resistance: "33.20" },
    { name: "中国联通", code: "600050", symbol: "SH600050", market: "SH", type: "stock", sector: "通信/6G", support: "4.98", resistance: "5.28" },
    { name: "中芯国际", code: "688981", symbol: "SH688981", market: "SH", type: "stock", sector: "半导体", support: "71.50", resistance: "76.80" },
    { name: "白酒基金LOF", code: "161725", symbol: "SZ161725", market: "SZ", type: "exchange_fund", sector: "消费", support: "", resistance: "" },
    { name: "易方达蓝筹精选混合", code: "005827", symbol: "OF005827", market: "OF", type: "open_fund", sector: "开放式基金", support: "", resistance: "" }
  ]
};

